### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by nishantnishu29** [glowbase/ssrf_redirect#1]
Usage: <PORT> <URL>
Traceback (most recent call last):
  File "/home/maa/Desktop/git/ssrf_redirect/ssrf_redirect.py", line 8, in <module>
    print("Usage: <PORT> <URL>").format(sys.argv[0])
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by sai8151** [comment]
> Usage: <PORT> <URL>
> Traceback (most recent call last):
>   File "/home/maa/Desktop/git/ssrf_redirect/ssrf_redirect.py", line 8, in <module>
>     print("Usage: <PORT> <URL>").format(sys.argv[0])
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'format'
> 

- Fix:
`print("Usage: {}".format(sys.argv[0]))`

**Comment by nishantnishu29** [comment]
thanks  brother
